use_frameworks!

platform :ios, '13.0'

target 'AgoraSttHelper_Example' do
  # develop
  pod 'AgoraSttHelper', :path => '../'

  # Agora Rtc SDK
  pod 'AgoraRtcEngine_iOS'
  # DarkEggKit
  pod 'DarkEggKit'
  
#  target 'AgoraSttHelper_Tests' do
#    inherit! :search_paths
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end

#
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
    # Check out: https://github.com/flutter/flutter/issues/123852
    # Workaround for Xcode 14.3:
    # system('sed -i \'\' \'44s/readlink/readlink -f/\' \'Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh\'')
end
