# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os:
  - osx
language: swift
osx_image: xcode11
branches:
  only:
    - develop

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/DarkEggKit.xcworkspace -scheme DarkEggKit-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' ONLY_ACTIVE_ARCH=NO | xcprettyTIVE_ARCH=NO | xcpretty
# - pod lib lint
